[phases.setup]
nixPkgs = ["nodejs"]

[start]
cmd = "npx serve -s . --cors --no-clipboard --no-request-logging"

[phases.install]
cmds = ["npm install -g serve"]

[headers]
"/*.css" = { "Cache-Control" = "no-cache, no-store, must-revalidate" }
"/*.js" = { "Cache-Control" = "no-cache, no-store, must-revalidate" }
"/*.html" = { "Cache-Control" = "no-cache, no-store, must-revalidate" } 